"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 22:42:52.824559
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stores_ok', sa.Integer(), nullable=False),
    sa.Column('stores_failed', sa.Integer(), nullable=False),
    sa.Column('deals_found', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('shortcut_url', sa.String(length=500), nullable=False),
    sa.Column('search_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=9), nullable=False),
    sa.Column('scraper', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('watch_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_id', name='uq_deal_store_external')
    )
    op.create_index('ix_deals_active_discount', 'deals', ['is_active', 'discount_pct'], unique=False)
    op.create_index(op.f('ix_deals_brand'), 'deals', ['brand'], unique=False)
    op.create_index(op.f('ix_deals_category'), 'deals', ['category'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_deal_id'), 'price_history', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_deal_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_deals_category'), table_name='deals')
    op.drop_index(op.f('ix_deals_brand'), table_name='deals')
    op.drop_index('ix_deals_active_discount', table_name='deals')
    op.drop_table('deals')
    op.drop_table('watch_terms')
    op.drop_table('stores')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
